language: node_js

node_js:
  - '8.9.4'

sudo: true

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE trainingtest WITH PASSWORD 'pass'" -U postgres
  - psql -c "ALTER ROLE trainingtest WITH LOGIN" -U postgres
  - psql -c "CREATE DATABASE trainingtest;" -U postgres
  - npm install
  - npm run migrations-test
